
--SET FOREIGN_KEY_CHECKS = 0;
--TRUNCATE account;

--TRUNCATE account_type;
 DELETE
FROM
	KEVINS_BANK;
--TRUNCATE bank_contact;
--TRUNCATE budget;
--TRUNCATE budget_transaction;
--TRUNCATE credential;
--TRUNCATE finances_user;
--TRUNCATE ifinances_keys;
--TRUNCATE time_test;
--TRUNCATE transaction;
--TRUNCATE user_account;
--TRUNCATE user_address;

--SET FOREIGN_KEY_CHECKS = 1;
 INSERT
	INTO
	KEVINS_BANK ( BANK_ID,
	NAME,
	ADDRESS_LINE_1,
	ADDRESS_LINE_2,
	CITY,
	STATE,
	ZIP_CODE,
	IS_INTERNATIONAL,
	LAST_UPDATED_BY,
	LAST_UPDATED_DATE,
	CREATED_BY,
	CREATED_DATE,
	ADDRESS_TYPE )
VALUES ( (
SELECT
	IDENTIFIER_VALUE
FROM
	USER_TABLE_GENERATOR
WHERE
	IDENTIFIER_NAME = 'KEVINS_BANK')+ 1,
'Second National Trust',
'301 Snowy Lane',
'Suite 2',
'Adams',
'PA',
'10003',
0,
'system',
TO_DATE('2014-11-01', 'YYYY-MM-DD'),
'system',
TO_DATE('2014-11-01', 'YYYY-MM-DD'),
'PRIMARY' );

UPDATE
	USER_TABLE_GENERATOR
SET
	IDENTIFIER_VALUE = (
	SELECT
		IDENTIFIER_VALUE
	FROM
		USER_TABLE_GENERATOR
	WHERE
		IDENTIFIER_NAME = 'KEVINS_BANK')+ 50
WHERE
	IDENTIFIER_NAME = 'KEVINS_BANK';

INSERT
	INTO
	KEVINS_BANK ( BANK_ID,
	NAME,
	ADDRESS_LINE_1,
	ADDRESS_LINE_2,
	CITY,
	STATE,
	ZIP_CODE,
	IS_INTERNATIONAL,
	LAST_UPDATED_BY,
	LAST_UPDATED_DATE,
	CREATED_BY,
	CREATED_DATE,
	ADDRESS_TYPE )
VALUES ( (
SELECT
	IDENTIFIER_VALUE
FROM
	USER_TABLE_GENERATOR
WHERE
	IDENTIFIER_NAME = 'KEVINS_BANK')+ 1,
'Third National Trust',
'Sunrise Drive',
'Suite 22',
'Jonestown',
'MI',
'12303',
0,
'system',
TO_DATE('2014-11-01', 'YYYY-MM-DD'),
'system',
TO_DATE('2014-11-01', 'YYYY-MM-DD'),
'PRIMARY' );

UPDATE
	USER_TABLE_GENERATOR
SET
	IDENTIFIER_VALUE = (
	SELECT
		IDENTIFIER_VALUE
	FROM
		USER_TABLE_GENERATOR
	WHERE
		IDENTIFIER_NAME = 'KEVINS_BANK')+ 50
WHERE
	IDENTIFIER_NAME = 'KEVINS_BANK';

INSERT
	INTO
	KEVINS_BANK ( BANK_ID,
	NAME,
	ADDRESS_LINE_1,
	ADDRESS_LINE_2,
	CITY,
	STATE,
	ZIP_CODE,
	IS_INTERNATIONAL,
	LAST_UPDATED_BY,
	LAST_UPDATED_DATE,
	CREATED_BY,
	CREATED_DATE,
	ADDRESS_TYPE )
VALUES ( (
SELECT
	IDENTIFIER_VALUE
FROM
	USER_TABLE_GENERATOR
WHERE
	IDENTIFIER_NAME = 'KEVINS_BANK')+ 1,
'Third National Trust',
'Bellvue',
'Suite 2',
'Newport',
'RI',
'18943',
0,
'system',
TO_DATE('2014-11-01', 'YYYY-MM-DD'),
'system',
TO_DATE('2014-11-01', 'YYYY-MM-DD'),
'PRIMARY' );

UPDATE
	USER_TABLE_GENERATOR
SET
	IDENTIFIER_VALUE = (
	SELECT
		IDENTIFIER_VALUE
	FROM
		USER_TABLE_GENERATOR
	WHERE
		IDENTIFIER_NAME = 'KEVINS_BANK')+ 50
WHERE
	IDENTIFIER_NAME = 'KEVINS_BANK';

INSERT
	INTO
	KEVINS_BANK ( BANK_ID,
	NAME,
	ADDRESS_LINE_1,
	ADDRESS_LINE_2,
	CITY,
	STATE,
	ZIP_CODE,
	IS_INTERNATIONAL,
	LAST_UPDATED_BY,
	LAST_UPDATED_DATE,
	CREATED_BY,
	CREATED_DATE,
	ADDRESS_TYPE )
VALUES ( (
SELECT
	IDENTIFIER_VALUE
FROM
	USER_TABLE_GENERATOR
WHERE
	IDENTIFIER_NAME = 'KEVINS_BANK')+ 1,
'Forth National Trust',
'403 Park Ave',
'Suite 221',
'Madison',
'WI',
'10003',
0,
'system',
TO_DATE('2014-11-01', 'YYYY-MM-DD'),
'system',
TO_DATE('2014-11-01', 'YYYY-MM-DD'),
'PRIMARY' );

COMMIT;